name: kernel

on:
  push:
    branches: [ "master" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_kernel_5-8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #- name: Cache VM
      #  uses: actions/cache@v3.0.5
      #  with:
          # A list of files, directories, and wildcard patterns to cache and restore
          #path: 
          # An explicit key for restoring and saving the cache
          #key: 
          # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
          # restore-keys: # optional
          # The chunk size used to split up large files during upload, in bytes
          # upload-chunk-size: # optional
      
      - name: Prepare runner
        run: sudo ./prepare_runner.sh
      
      - name: Build VM
        run: sudo ./build_vm.sh
      
      - name: Launch VM
        run: sudo ./install_vm.sh

      - name: Run test script
        run: ./test.sh
